/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import controller.MainFrameController;
import java.awt.Component;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.JTabbedPane;

/**
 *
 * @author Dikki Haryadi
 */
public class MainFrame extends javax.swing.JFrame {
    MainFrameController menuController=new MainFrameController();
   
     
    /**
     * Creates new form MainFrame
     */
    public MainFrame() {
        initComponents();
        setExtendedState(JFrame.MAXIMIZED_BOTH);
        MasterMenu.setEnabled(true);
        menuController.setVisible(customer, product, supplier, uom, user, receiving, cashier);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem3 = new javax.swing.JMenuItem();
        tabbedPane = new javax.swing.JTabbedPane();
        customerIcon = new javax.swing.JLabel();
        productIcon = new javax.swing.JLabel();
        supplierIcon = new javax.swing.JLabel();
        uomIcon = new javax.swing.JLabel();
        userIcon = new javax.swing.JLabel();
        receivingIcon = new javax.swing.JLabel();
        stockIcon = new javax.swing.JLabel();
        cashierIcon = new javax.swing.JLabel();
        product = new javax.swing.JLabel();
        productB = new javax.swing.JLabel();
        customer = new javax.swing.JLabel();
        customerB = new javax.swing.JLabel();
        supplier = new javax.swing.JLabel();
        supplierB = new javax.swing.JLabel();
        uom = new javax.swing.JLabel();
        uomB = new javax.swing.JLabel();
        user = new javax.swing.JLabel();
        userB = new javax.swing.JLabel();
        receiving = new javax.swing.JLabel();
        receivingB = new javax.swing.JLabel();
        cashier = new javax.swing.JLabel();
        cashierB = new javax.swing.JLabel();
        bg = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        FileMenu = new javax.swing.JMenu();
        LoginMenuItem = new javax.swing.JMenuItem();
        ExitMenuItem = new javax.swing.JMenuItem();
        MasterMenu = new javax.swing.JMenu();
        CustomerMenuItem = new javax.swing.JMenuItem();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        ProductMenuItem = new javax.swing.JMenuItem();
        jSeparator2 = new javax.swing.JPopupMenu.Separator();
        SupplierMenuItem = new javax.swing.JMenuItem();
        jSeparator3 = new javax.swing.JPopupMenu.Separator();
        UomMenuItem = new javax.swing.JMenuItem();
        jSeparator4 = new javax.swing.JPopupMenu.Separator();
        UserMenuItem = new javax.swing.JMenuItem();
        InventoryMenu = new javax.swing.JMenu();
        ReceivingMenuItem = new javax.swing.JMenuItem();
        jSeparator5 = new javax.swing.JPopupMenu.Separator();
        jSeparator6 = new javax.swing.JPopupMenu.Separator();
        ProductStockMenuItem = new javax.swing.JMenuItem();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenuItem4 = new javax.swing.JMenuItem();
        HelpMenu = new javax.swing.JMenu();
        AboutMenuItem = new javax.swing.JMenuItem();

        jMenuItem1.setText("jMenuItem1");

        jMenuItem3.setText("jMenuItem3");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tabbedPane.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        getContentPane().add(tabbedPane, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 30, 1120, 610));

        customerIcon.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                customerIconMouseClicked(evt);
            }
        });
        getContentPane().add(customerIcon, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 10, 170, 20));

        productIcon.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                productIconMouseClicked(evt);
            }
        });
        getContentPane().add(productIcon, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 30, 170, 20));

        supplierIcon.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                supplierIconMouseClicked(evt);
            }
        });
        getContentPane().add(supplierIcon, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 20, 170, 20));

        uomIcon.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                uomIconMouseClicked(evt);
            }
        });
        getContentPane().add(uomIcon, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 20, 170, 20));

        userIcon.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                userIconMouseClicked(evt);
            }
        });
        getContentPane().add(userIcon, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 30, 170, 20));

        receivingIcon.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                receivingIconMouseClicked(evt);
            }
        });
        getContentPane().add(receivingIcon, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 30, 170, 20));

        stockIcon.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                stockIconMouseClicked(evt);
            }
        });
        getContentPane().add(stockIcon, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 30, 170, 20));

        cashierIcon.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cashierIconMouseClicked(evt);
            }
        });
        getContentPane().add(cashierIcon, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 30, 170, 20));

        product.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/images/product.png"))); // NOI18N
        product.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                productMouseClicked(evt);
            }
        });
        getContentPane().add(product, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 140, 170, 20));

        productB.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/images/product_black.png"))); // NOI18N
        productB.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                productBMouseClicked(evt);
            }
        });
        getContentPane().add(productB, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 140, 180, 20));

        customer.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/images/customer.png"))); // NOI18N
        customer.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                customerMouseClicked(evt);
            }
        });
        getContentPane().add(customer, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 120, 170, 20));

        customerB.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/images/customer_black.png"))); // NOI18N
        customerB.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                customerBMouseClicked(evt);
            }
        });
        getContentPane().add(customerB, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 120, 180, 20));

        supplier.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/images/supplier.png"))); // NOI18N
        supplier.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                supplierMouseClicked(evt);
            }
        });
        getContentPane().add(supplier, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 160, 170, 20));

        supplierB.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/images/supplier_black.png"))); // NOI18N
        supplierB.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                supplierBMouseClicked(evt);
            }
        });
        getContentPane().add(supplierB, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 160, 190, 20));

        uom.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/images/uom.png"))); // NOI18N
        uom.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                uomMouseClicked(evt);
            }
        });
        getContentPane().add(uom, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 180, 170, 20));

        uomB.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/images/uom_black.png"))); // NOI18N
        uomB.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                uomBMouseClicked(evt);
            }
        });
        getContentPane().add(uomB, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 180, 180, 20));

        user.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/images/user.png"))); // NOI18N
        user.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                userMouseClicked(evt);
            }
        });
        getContentPane().add(user, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 200, 170, 20));

        userB.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/images/user_black.png"))); // NOI18N
        userB.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                userBMouseClicked(evt);
            }
        });
        getContentPane().add(userB, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 200, 170, 20));

        receiving.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/images/receiving.png"))); // NOI18N
        receiving.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                receivingMouseClicked(evt);
            }
        });
        getContentPane().add(receiving, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 260, 180, 20));

        receivingB.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/images/receiving_black.png"))); // NOI18N
        receivingB.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                receivingBMouseClicked(evt);
            }
        });
        getContentPane().add(receivingB, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 260, 170, 20));

        cashier.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/images/cashier.png"))); // NOI18N
        cashier.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cashierMouseClicked(evt);
            }
        });
        getContentPane().add(cashier, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 330, 190, 20));

        cashierB.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/images/cashier_black.png"))); // NOI18N
        cashierB.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cashierBMouseClicked(evt);
            }
        });
        getContentPane().add(cashierB, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 330, 170, 20));

        bg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/images/menu.png"))); // NOI18N
        getContentPane().add(bg, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1340, 660));

        FileMenu.setText("File");

        LoginMenuItem.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_L, java.awt.event.InputEvent.ALT_MASK));
        LoginMenuItem.setText("Login");
        LoginMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LoginMenuItemActionPerformed(evt);
            }
        });
        FileMenu.add(LoginMenuItem);

        ExitMenuItem.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_E, java.awt.event.InputEvent.ALT_MASK));
        ExitMenuItem.setText("Exit");
        ExitMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ExitMenuItemActionPerformed(evt);
            }
        });
        FileMenu.add(ExitMenuItem);

        jMenuBar1.add(FileMenu);

        MasterMenu.setText("Master Data");

        CustomerMenuItem.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_C, java.awt.event.InputEvent.ALT_MASK));
        CustomerMenuItem.setText("Pelanggan");
        CustomerMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CustomerMenuItemActionPerformed(evt);
            }
        });
        MasterMenu.add(CustomerMenuItem);
        MasterMenu.add(jSeparator1);

        ProductMenuItem.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_P, java.awt.event.InputEvent.ALT_MASK));
        ProductMenuItem.setText("Barang");
        ProductMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ProductMenuItemActionPerformed(evt);
            }
        });
        MasterMenu.add(ProductMenuItem);
        MasterMenu.add(jSeparator2);

        SupplierMenuItem.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_S, java.awt.event.InputEvent.ALT_MASK));
        SupplierMenuItem.setText("Supplier");
        SupplierMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SupplierMenuItemActionPerformed(evt);
            }
        });
        MasterMenu.add(SupplierMenuItem);
        MasterMenu.add(jSeparator3);

        UomMenuItem.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_U, java.awt.event.InputEvent.ALT_MASK));
        UomMenuItem.setText("Satuan");
        UomMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UomMenuItemActionPerformed(evt);
            }
        });
        MasterMenu.add(UomMenuItem);
        MasterMenu.add(jSeparator4);

        UserMenuItem.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_R, java.awt.event.InputEvent.ALT_MASK));
        UserMenuItem.setText("User");
        UserMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UserMenuItemActionPerformed(evt);
            }
        });
        MasterMenu.add(UserMenuItem);

        jMenuBar1.add(MasterMenu);

        InventoryMenu.setText("Inventory Data");

        ReceivingMenuItem.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_R, java.awt.event.InputEvent.ALT_MASK));
        ReceivingMenuItem.setText("Pembelian");
        ReceivingMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ReceivingMenuItemActionPerformed(evt);
            }
        });
        InventoryMenu.add(ReceivingMenuItem);
        InventoryMenu.add(jSeparator5);
        InventoryMenu.add(jSeparator6);

        ProductStockMenuItem.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_P, java.awt.event.InputEvent.ALT_MASK));
        ProductStockMenuItem.setText("Report Pembelian");
        ProductStockMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ProductStockMenuItemActionPerformed(evt);
            }
        });
        InventoryMenu.add(ProductStockMenuItem);

        jMenuBar1.add(InventoryMenu);

        jMenu1.setText("Transaction");

        jMenuItem2.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_T, java.awt.event.InputEvent.ALT_MASK));
        jMenuItem2.setText("Penjualan");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem2);

        jMenuItem4.setText("Report Penjualan");
        jMenu1.add(jMenuItem4);

        jMenuBar1.add(jMenu1);

        HelpMenu.setText("Help");

        AboutMenuItem.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_A, java.awt.event.InputEvent.ALT_MASK));
        AboutMenuItem.setText("About");
        AboutMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AboutMenuItemActionPerformed(evt);
            }
        });
        HelpMenu.add(AboutMenuItem);

        jMenuBar1.add(HelpMenu);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ProductMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ProductMenuItemActionPerformed
        TabProduct product=new TabProduct();
        tabbedPane.addTab("Product Data", product);
        tabbedPane.setTabComponentAt(tabbedPane.indexOfComponent(product),new ButtonTabComponent(tabbedPane));
    }//GEN-LAST:event_ProductMenuItemActionPerformed

    private void UomMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UomMenuItemActionPerformed
        TabUom uom=new TabUom();
        tabbedPane.addTab("Unit Of Measure Data", uom);
        tabbedPane.setTabComponentAt(tabbedPane.indexOfComponent(uom),new ButtonTabComponent(tabbedPane));
    }//GEN-LAST:event_UomMenuItemActionPerformed

    private void SupplierMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SupplierMenuItemActionPerformed
        TabSupplier supplier=new TabSupplier();
        tabbedPane.addTab("Supplier Data",supplier);
        tabbedPane.setTabComponentAt(tabbedPane.indexOfComponent(supplier),new ButtonTabComponent(tabbedPane));
    }//GEN-LAST:event_SupplierMenuItemActionPerformed

    private void ExitMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ExitMenuItemActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ExitMenuItemActionPerformed

    private void LoginMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LoginMenuItemActionPerformed
        // TODO add your handling code here:
       
        
    }//GEN-LAST:event_LoginMenuItemActionPerformed

    private void CustomerMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CustomerMenuItemActionPerformed
       TabCustomer customer=new TabCustomer();
       tabbedPane.addTab("Customer Data",customer);
       tabbedPane.setTabComponentAt(tabbedPane.indexOfComponent(customer),new ButtonTabComponent(tabbedPane));
    }//GEN-LAST:event_CustomerMenuItemActionPerformed

    private void UserMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UserMenuItemActionPerformed
        TabUser user=new TabUser();
        tabbedPane.addTab("User Data",user);
        tabbedPane.setTabComponentAt(tabbedPane.indexOfComponent(user),new ButtonTabComponent(tabbedPane));
    }//GEN-LAST:event_UserMenuItemActionPerformed

    private void ReceivingMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ReceivingMenuItemActionPerformed
        TabPembelian receiving=new TabPembelian();
        tabbedPane.addTab("Receiving Data",receiving);
        tabbedPane.setTabComponentAt(tabbedPane.indexOfComponent(receiving),new ButtonTabComponent(tabbedPane));
    }//GEN-LAST:event_ReceivingMenuItemActionPerformed

    private void ProductStockMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ProductStockMenuItemActionPerformed
       
    }//GEN-LAST:event_ProductStockMenuItemActionPerformed

    private void AboutMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AboutMenuItemActionPerformed
        
    }//GEN-LAST:event_AboutMenuItemActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
       TabPenjualan tran=new TabPenjualan();
       tabbedPane.add("Penjualan",tran);
       tabbedPane.setTabComponentAt(tabbedPane.indexOfComponent(tran),new ButtonTabComponent(tabbedPane));
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void customerBMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_customerBMouseClicked
     
           customer.setVisible(true);
           TabCustomer cust=new TabCustomer();
           tabbedPane.addTab("Data Pelanggan",cust);
           tabbedPane.setTabComponentAt(tabbedPane.indexOfComponent(cust),new ButtonTabComponent(tabbedPane));
           tabbedPane.setSelectedComponent(cust);
       
    }//GEN-LAST:event_customerBMouseClicked

    private void productBMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_productBMouseClicked
           product.setVisible(true);
           TabProduct product=new TabProduct();
           tabbedPane.addTab("Data Barang",product);
           tabbedPane.setTabComponentAt(tabbedPane.indexOfComponent(product),new ButtonTabComponent(tabbedPane));
           tabbedPane.setSelectedComponent(product);
    }//GEN-LAST:event_productBMouseClicked

    private void supplierBMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_supplierBMouseClicked
            supplier.setVisible(true);
            TabSupplier supp=new TabSupplier();
            tabbedPane.addTab("Data Supplier",supp);
            tabbedPane.setTabComponentAt(tabbedPane.indexOfComponent(supp),new ButtonTabComponent(tabbedPane));
            tabbedPane.setSelectedComponent(supp);
        
    }//GEN-LAST:event_supplierBMouseClicked

    private void uomBMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_uomBMouseClicked
            uom.setVisible(true);
            TabUom uom=new TabUom();
            tabbedPane.addTab("Data Satuan",uom);
            tabbedPane.setTabComponentAt(tabbedPane.indexOfComponent(uom),new ButtonTabComponent(tabbedPane));
            tabbedPane.setSelectedComponent(uom);
        
    }//GEN-LAST:event_uomBMouseClicked

    private void userBMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_userBMouseClicked
       
            user.setVisible(true);
            TabUser user=new TabUser();
            tabbedPane.addTab("Data User",user);
            tabbedPane.setTabComponentAt(tabbedPane.indexOfComponent(user),new ButtonTabComponent(tabbedPane));
            tabbedPane.setSelectedComponent(user);
        
    }//GEN-LAST:event_userBMouseClicked

    private void receivingBMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_receivingBMouseClicked
            receiving.setVisible(true);
            TabPembelian receiving=new TabPembelian();
            tabbedPane.addTab("Data Pembelian Barang",receiving);
            tabbedPane.setTabComponentAt(tabbedPane.indexOfComponent(receiving),new ButtonTabComponent(tabbedPane));
            tabbedPane.setSelectedComponent(receiving);
        
    }//GEN-LAST:event_receivingBMouseClicked

    private void cashierBMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cashierBMouseClicked
            cashier.setVisible(true);
            TabPenjualan transaction=new TabPenjualan();
            tabbedPane.addTab("Data Penjualan",transaction);
            tabbedPane.setTabComponentAt(tabbedPane.indexOfComponent(transaction),new ButtonTabComponent(tabbedPane));
            tabbedPane.setSelectedComponent(transaction);
        
    }//GEN-LAST:event_cashierBMouseClicked

    private void customerMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_customerMouseClicked
       
       Component i=tabbedPane.getSelectedComponent();
        if(i!=null){
            tabbedPane.remove(i);
            customer.setVisible(false);    
            customerB.setVisible(true);
        }else{
        customer.setVisible(false);
        }
        
       
    }//GEN-LAST:event_customerMouseClicked

    private void productMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_productMouseClicked
        Component i=tabbedPane.getSelectedComponent();
        if(i!=null){
            tabbedPane.remove(i);
            product.setVisible(true);
            product.setVisible(false);
        }
        else{
            product.setVisible(false);
        }
    }//GEN-LAST:event_productMouseClicked

    private void supplierMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_supplierMouseClicked
         Component i=tabbedPane.getSelectedComponent();
        if(i!=null){
            tabbedPane.remove(i);
            supplier.setVisible(false);    
            supplierB.setVisible(true);
        }
        else{
            supplier.setVisible(false);
        }
    }//GEN-LAST:event_supplierMouseClicked

    private void uomMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_uomMouseClicked
        Component i=tabbedPane.getSelectedComponent();
        if(i!=null){
            tabbedPane.remove(i);
            uom.setVisible(false);    
            uomB.setVisible(true);
        }else{
            uom.setVisible(false);
        }
    }//GEN-LAST:event_uomMouseClicked

    private void userMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_userMouseClicked
        
        Component i=tabbedPane.getSelectedComponent();
        if(i!=null){
            tabbedPane.remove(i);
            user.setVisible(false);    
            userB.setVisible(true);
        }else{
            user.setVisible(false);
        }
    }//GEN-LAST:event_userMouseClicked

    private void receivingMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_receivingMouseClicked
        Component i=tabbedPane.getSelectedComponent();
        if(i!=null){
            tabbedPane.remove(i);
            receiving.setVisible(false);    
            receivingB.setVisible(true);
        }else{
            receiving.setVisible(false);
        }
        
    }//GEN-LAST:event_receivingMouseClicked

    private void cashierMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cashierMouseClicked
        Component i=tabbedPane.getSelectedComponent();
        if(i!=null){
            tabbedPane.remove(i);
            cashier.setVisible(false);    
            cashierB.setVisible(true);
        }else{
            cashier.setVisible(false); 
        }
    }//GEN-LAST:event_cashierMouseClicked

    private void customerIconMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_customerIconMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_customerIconMouseClicked

    private void productIconMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_productIconMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_productIconMouseClicked

    private void supplierIconMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_supplierIconMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_supplierIconMouseClicked

    private void uomIconMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_uomIconMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_uomIconMouseClicked

    private void userIconMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_userIconMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_userIconMouseClicked

    private void receivingIconMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_receivingIconMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_receivingIconMouseClicked

    private void stockIconMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_stockIconMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_stockIconMouseClicked

    private void cashierIconMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cashierIconMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_cashierIconMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem AboutMenuItem;
    private javax.swing.JMenuItem CustomerMenuItem;
    private javax.swing.JMenuItem ExitMenuItem;
    private javax.swing.JMenu FileMenu;
    private javax.swing.JMenu HelpMenu;
    private javax.swing.JMenu InventoryMenu;
    private javax.swing.JMenuItem LoginMenuItem;
    private javax.swing.JMenu MasterMenu;
    private javax.swing.JMenuItem ProductMenuItem;
    private javax.swing.JMenuItem ProductStockMenuItem;
    private javax.swing.JMenuItem ReceivingMenuItem;
    private javax.swing.JMenuItem SupplierMenuItem;
    private javax.swing.JMenuItem UomMenuItem;
    private javax.swing.JMenuItem UserMenuItem;
    private javax.swing.JLabel bg;
    private javax.swing.JLabel cashier;
    private javax.swing.JLabel cashierB;
    private javax.swing.JLabel cashierIcon;
    private javax.swing.JLabel customer;
    private javax.swing.JLabel customerB;
    private javax.swing.JLabel customerIcon;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    private javax.swing.JPopupMenu.Separator jSeparator2;
    private javax.swing.JPopupMenu.Separator jSeparator3;
    private javax.swing.JPopupMenu.Separator jSeparator4;
    private javax.swing.JPopupMenu.Separator jSeparator5;
    private javax.swing.JPopupMenu.Separator jSeparator6;
    private javax.swing.JLabel product;
    private javax.swing.JLabel productB;
    private javax.swing.JLabel productIcon;
    private javax.swing.JLabel receiving;
    private javax.swing.JLabel receivingB;
    private javax.swing.JLabel receivingIcon;
    private javax.swing.JLabel stockIcon;
    private javax.swing.JLabel supplier;
    private javax.swing.JLabel supplierB;
    private javax.swing.JLabel supplierIcon;
    private javax.swing.JTabbedPane tabbedPane;
    private javax.swing.JLabel uom;
    private javax.swing.JLabel uomB;
    private javax.swing.JLabel uomIcon;
    private javax.swing.JLabel user;
    private javax.swing.JLabel userB;
    private javax.swing.JLabel userIcon;
    // End of variables declaration//GEN-END:variables
}
